### PR TITLE
Flak init

### PR DESCRIPTION
**Pull request by DaboRestrepo**
The first API things

### CODE REVIEW

**Review by DanielDevDu — COMMENTED** [review]
Me trying to make a good commit with emojis!! jajaja

**Review by DaboRestrepo — COMMENTED** [review]
We need to fix all the pycodestyle in the State view.

**Review by DanielDevDu — COMMENTED** [review]
We need to update GET and DELETE methods using aux_funcs

**Review by DanielDevDu — COMMENTED** [review]
I think that is a good idea use Response in the views

**Review by DaboRestrepo — COMMENTED** [review]
Fix the order in the view init.

**Review by DaboRestrepo — COMMENTED** [review]
Update the init with users.

**Review by DanielDevDu — COMMENTED** [review]
Fix pycodestyle in views

**Review by DanielDevDu — COMMENTED** [review]
Pycodestyle Work!!

**Pull request merged**
